import DesignTokens from './DesignTokens';

export const themes = {
  forest: {
    id: 'forest',
    name: '森林主题',
    icon: '🌲',
    description: '沉浸在自然的宁静中',
    colors: {
      primary: DesignTokens.colors.morandi.green,
      secondary: DesignTokens.colors.morandi.purple,
      background: '#E8F5E9',
      gradient: 'linear-gradient(135deg, #C7F0DB 0%, #A8D8EA 100%)',
      card: 'rgba(255, 255, 255, 0.7)',
      text: '#1F2937',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.green,
      '4-4': DesignTokens.colors.morandi.blue,
      '5-5': DesignTokens.colors.morandi.purple,
      '6-6': DesignTokens.colors.morandi.pink,
    },
  },
  ocean: {
    id: 'ocean',
    name: '海洋主题',
    icon: '🌊',
    description: '感受大海的宽广与平静',
    colors: {
      primary: DesignTokens.colors.morandi.blue,
      secondary: DesignTokens.colors.morandi.purple,
      background: '#E0F7FA',
      gradient: 'linear-gradient(135deg, #A8D8EA 0%, #C4B7E0 100%)',
      card: 'rgba(255, 255, 255, 0.7)',
      text: '#1E3A8A',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.blue,
      '4-4': DesignTokens.colors.morandi.purple,
      '5-5': DesignTokens.colors.morandi.green,
      '6-6': DesignTokens.colors.morandi.pink,
    },
  },
  sunset: {
    id: 'sunset',
    name: '日落主题',
    icon: '🌅',
    description: '享受温暖的黄昏时光',
    colors: {
      primary: DesignTokens.colors.morandi.pink,
      secondary: DesignTokens.colors.morandi.coral,
      background: '#FFF3E0',
      gradient: 'linear-gradient(135deg, #E8C4D8 0%, #F5B8A8 100%)',
      card: 'rgba(255, 255, 255, 0.7)',
      text: '#4A2F2A',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.pink,
      '4-4': DesignTokens.colors.morandi.coral,
      '5-5': DesignTokens.colors.morandi.yellow,
      '6-6': DesignTokens.colors.morandi.purple,
    },
  },
  lavender: {
    id: 'lavender',
    name: '薰衣草主题',
    icon: '💜',
    description: '舒缓的紫色梦境',
    colors: {
      primary: DesignTokens.colors.morandi.purple,
      secondary: DesignTokens.colors.morandi.lavender,
      background: '#F3E5F5',
      gradient: 'linear-gradient(135deg, #C4B7E0 0%, #D4C8E8 100%)',
      card: 'rgba(255, 255, 255, 0.7)',
      text: '#4A1D96',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.purple,
      '4-4': DesignTokens.colors.morandi.lavender,
      '5-5': DesignTokens.colors.morandi.pink,
      '6-6': DesignTokens.colors.morandi.blue,
    },
  },
  meadow: {
    id: 'meadow',
    name: '草地主题',
    icon: '🌼',
    description: '阳光明媚的草地',
    colors: {
      primary: DesignTokens.colors.morandi.yellow,
      secondary: DesignTokens.colors.morandi.green,
      background: '#FFFDE7',
      gradient: 'linear-gradient(135deg, #F7E9B8 0%, #C7F0DB 100%)',
      card: 'rgba(255, 255, 255, 0.7)',
      text: '#3F3F46',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.yellow,
      '4-4': DesignTokens.colors.morandi.green,
      '5-5': DesignTokens.colors.morandi.blue,
      '6-6': DesignTokens.colors.morandi.pink,
    },
  },
  nightSky: {
    id: 'nightSky',
    name: '夜空主题',
    icon: '🌌',
    description: '静谧的星空夜晚',
    colors: {
      primary: DesignTokens.colors.morandi.purpleLight,
      secondary: DesignTokens.colors.morandi.blue,
      background: '#1E1B4B',
      gradient: 'linear-gradient(135deg, #2C3E50 0%, #4A1D96 100%)',
      card: 'rgba(255, 255, 255, 0.1)',
      text: '#FFFFFF',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.purpleLight,
      '4-4': DesignTokens.colors.morandi.blueLight,
      '5-5': DesignTokens.colors.morandi.pinkLight,
      '6-6': DesignTokens.colors.morandi.lavender,
    },
  },
  morning: {
    id: 'morning',
    name: '晨曦主题',
    icon: '🌅',
    description: '温暖的清晨阳光',
    colors: {
      primary: '#FFB347',
      secondary: '#FFA07A',
      background: '#FFF8DC',
      gradient: 'linear-gradient(135deg, #FFE5B4 0%, #FFB347 100%)',
      card: 'rgba(255, 255, 255, 0.8)',
      text: '#4A2F2A',
    },
    breathing: {
      '4-7-8': '#FFB347',
      '4-4': '#FFA07A',
      '5-5': '#FFD700',
      '6-6': '#FFA500',
    },
  },
  garden: {
    id: 'garden',
    name: '花园主题',
    icon: '🌸',
    description: '多彩的花园世界',
    colors: {
      primary: DesignTokens.colors.morandi.pink,
      secondary: DesignTokens.colors.morandi.coral,
      background: '#FFF0F5',
      gradient: 'linear-gradient(135deg, #FFE4E1 0%, #FDE2E4 100%)',
      card: 'rgba(255, 255, 255, 0.85)',
      text: '#4A2F2A',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.pink,
      '4-4': DesignTokens.colors.morandi.coral,
      '5-5': DesignTokens.colors.morandi.yellow,
      '6-6': DesignTokens.colors.morandi.green,
    },
  },
  snow: {
    id: 'snow',
    name: '雪山主题',
    icon: '❄️',
    description: '纯净的冰雪世界',
    colors: {
      primary: DesignTokens.colors.morandi.blueLight,
      secondary: DesignTokens.colors.morandi.purpleLight,
      background: '#E8F4F8',
      gradient: 'linear-gradient(135deg, #E0F7FA 0%, #C5E5F2 100%)',
      card: 'rgba(255, 255, 255, 0.85)',
      text: '#1E3A8A',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.morandi.blueLight,
      '4-4': DesignTokens.colors.morandi.purpleLight,
      '5-5': DesignTokens.colors.morandi.greenLight,
      '6-6': DesignTokens.colors.morandi.pinkLight,
    },
  },
  minimal: {
    id: 'minimal',
    name: '极简主题',
    icon: '⬜',
    description: '简约的黑白世界',
    colors: {
      primary: DesignTokens.colors.neutral.gray800,
      secondary: DesignTokens.colors.neutral.gray600,
      background: '#FFFFFF',
      gradient: 'linear-gradient(135deg, #F9FAFB 0%, #E5E7EB 100%)',
      card: 'rgba(255, 255, 255, 0.9)',
      text: '#1F2937',
    },
    breathing: {
      '4-7-8': DesignTokens.colors.neutral.gray600,
      '4-4': DesignTokens.colors.neutral.gray700,
      '5-5': DesignTokens.colors.neutral.gray500,
      '6-6': DesignTokens.colors.neutral.gray400,
    },
  },
  cherry: {
    id: 'cherry',
    name: '樱花主题',
    icon: '🌸',
    description: '浪漫的樱花季节',
    colors: {
      primary: '#FFB7C5',
      secondary: '#FFA07A',
      background: '#FFF5F7',
      gradient: 'linear-gradient(135deg, #FFE4E1 0%, #FFB7C5 100%)',
      card: 'rgba(255, 255, 255, 0.85)',
      text: '#4A2F2A',
    },
    breathing: {
      '4-7-8': '#FFB7C5',
      '4-4': '#FFA07A',
      '5-5': '#FFD1DC',
      '6-6': '#FF9AA2',
    },
  },
  aurora: {
    id: 'aurora',
    name: '极光主题',
    icon: '🌌',
    description: '神秘的极光色彩',
    colors: {
      primary: '#00CED1',
      secondary: '#9370DB',
      background: '#0F172A',
      gradient: 'linear-gradient(135deg, #1E3A8A 0%, #00CED1 100%)',
      card: 'rgba(255, 255, 255, 0.1)',
      text: '#FFFFFF',
    },
    breathing: {
      '4-7-8': '#00CED1',
      '4-4': '#9370DB',
      '5-5': '#48D1CC',
      '6-6': '#FF6B6B',
    },
  },
};

export const defaultTheme = 'forest';

export const getTheme = (themeId) => {
  return themes[themeId] || themes[defaultTheme];
};

export default themes;
